services:
  - type: web
    name: flower-backend
    env: java
    plan: free
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/*.jar"
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://switchyard.proxy.rlwy.net:15887/railway
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: GlVavknzrZCAaZZxJrsKVYqQXGSZwTeh
