spring.application.name=flower

# ===============================
# MONGODB ATLAS CONFIGURATION
# ===============================

spring.data.mongodb.uri=${MONGODB_URI}

# ===============================
# SERVER CONFIG
# ===============================

server.port=${PORT:8080}