spring.application.name=flower

# ===============================
# MONGODB ATLAS CONFIGURATION
# ===============================

spring.data.mongodb.uri=mongodb+srv://Shivam:Shivam979580@cluster0.ez2svpu.mongodb.net/flowerdb?retryWrites=true&w=majority

# ===============================
# SERVER CONFIG
# ===============================

server.port=8080