# ===============================
# APPLICATION NAME
# ===============================

spring.application.name=flower


# ===============================
# MONGODB ATLAS CONFIGURATION
# ===============================

spring.data.mongodb.uri=mongodb+srv://Shivam:Shivam979580@cluster0.ez2svpu.mongodb.net/flowerdb?retryWrites=true&w=majority


# ===============================
# SERVER CONFIG
# ===============================

server.port=8080


# ===============================
# EMAIL SMTP CONFIGURATION
# ===============================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shivamsaini6013@gmail.com
spring.mail.password=fadfgbxdwrruhyvh

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true